### ISSUE TITLE
Bad display in terminal

### ISSUE THREAD

**Issue by daedhel** [bougyman/wifish#12]
Hi,

The display is problematic in my terminal.

I am using voidlinux, updated today. Here is my uname -a :

Linux j-t410 4.19.34_1 #1 SMP PREEMPT Sun Apr 7 08:49:36 UTC 2019 x86_64 GNU/Linux

Here is wifish's version : wifish-1.1.4_1
![Screenshot_20190424_090157](https://user-images.githubusercontent.com/110817/56661738-5df1aa80-6670-11e9-8c7b-da06be502584.png)

**Comment by bougyman** [comment]
That is odd, and I'm unable to reproduce. What terminal is that?

**Comment by bougyman** [comment]
never got the terminal that this was problematic with, closing
