### ISSUE TITLE
Feature request: Connecting to WPA2-{PEAP,TTLS}

### ISSUE THREAD

**Issue by skrzyp** [bougyman/wifish#4]
Add support to connect with networks using 802.11X authentication (identity/password or key-based) like Eduroam or some ISPs' "free" hot-spots for their customers.

Example config for wpa_supplicant:

```
# It can differ depending on network configuration and administrator's requirements, read manual
network={
    ssid="BigCOM Free-WiFi"
    key_mgmt=WPA-EAP
    eap=PEAP
    identity="johnsmith"
    password="passw0rd"
    phase2="auth=MSCHAPv2"
}
```

**Comment by bougyman** [comment]
Will do tonight, I need a network to test this with. If you want to PR it do it against latest master, I've added the ability to run wifish non-interactively. In a non-interactive mode should wifish accept 

```
echo 'identity:password'|wifish c "BigCOM Free-Wifi"
```

?

**Comment by bougyman** [comment]
Not going to do Cert auth yet, this will be a separate feature later if/when it's desired. To use cert auth now you would set up an EAP connection and manually provide the cert paths. (with wpa_cli).
