### ISSUE TITLE
wifish should call wpa_passphrase to generate passphrase instead of using PSK

### ISSUE THREAD

**Issue by guinanseyebrows** [bougyman/wifish#5]
When joining a new network, wifish adds the PSK to wpa_supplicant.conf, which will not allow you to join some/all networks.
Instead, it should pass the PSK to wpa_passphrase to generate the correct passphrase to use with wpa_supplicant before adding it to the .conf file/connecting.

**Comment by bougyman** [comment]
Will do, thanks.

**Comment by bougyman** [comment]
Can you get me a PR for this?

**Comment by bougyman** [comment]
Working on this over the weekend.
